// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messageUpdate.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "../../../Headers/Utils/Socket/messageUpdate.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* messageUpdate_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  messageUpdate_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_messageUpdate_2eproto() {
  protobuf_AddDesc_messageUpdate_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "messageUpdate.proto");
  GOOGLE_CHECK(file != NULL);
  messageUpdate_descriptor_ = file->message_type(0);
  static const int messageUpdate_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(messageUpdate, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(messageUpdate, tipo_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(messageUpdate, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(messageUpdate, y_),
  };
  messageUpdate_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      messageUpdate_descriptor_,
      messageUpdate::default_instance_,
      messageUpdate_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(messageUpdate, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(messageUpdate, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(messageUpdate));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_messageUpdate_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    messageUpdate_descriptor_, &messageUpdate::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_messageUpdate_2eproto() {
  delete messageUpdate::default_instance_;
  delete messageUpdate_reflection_;
}

void protobuf_AddDesc_messageUpdate_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023messageUpdate.proto\"\?\n\rmessageUpdate\022\n"
    "\n\002id\030\001 \002(\005\022\014\n\004tipo\030\002 \002(\t\022\t\n\001x\030\003 \001(\005\022\t\n\001y"
    "\030\004 \001(\005", 86);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "messageUpdate.proto", &protobuf_RegisterTypes);
  messageUpdate::default_instance_ = new messageUpdate();
  messageUpdate::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_messageUpdate_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_messageUpdate_2eproto {
  StaticDescriptorInitializer_messageUpdate_2eproto() {
    protobuf_AddDesc_messageUpdate_2eproto();
  }
} static_descriptor_initializer_messageUpdate_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int messageUpdate::kIdFieldNumber;
const int messageUpdate::kTipoFieldNumber;
const int messageUpdate::kXFieldNumber;
const int messageUpdate::kYFieldNumber;
#endif  // !_MSC_VER

messageUpdate::messageUpdate()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:messageUpdate)
}

void messageUpdate::InitAsDefaultInstance() {
}

messageUpdate::messageUpdate(const messageUpdate& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:messageUpdate)
}

void messageUpdate::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  id_ = 0;
  tipo_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  x_ = 0;
  y_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

messageUpdate::~messageUpdate() {
  // @@protoc_insertion_point(destructor:messageUpdate)
  SharedDtor();
}

void messageUpdate::SharedDtor() {
  if (tipo_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete tipo_;
  }
  if (this != default_instance_) {
  }
}

void messageUpdate::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* messageUpdate::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return messageUpdate_descriptor_;
}

const messageUpdate& messageUpdate::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_messageUpdate_2eproto();
  return *default_instance_;
}

messageUpdate* messageUpdate::default_instance_ = NULL;

messageUpdate* messageUpdate::New() const {
  return new messageUpdate;
}

void messageUpdate::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<messageUpdate*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 15) {
    ZR_(id_, y_);
    if (has_tipo()) {
      if (tipo_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        tipo_->clear();
      }
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool messageUpdate::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:messageUpdate)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_tipo;
        break;
      }

      // required string tipo = 2;
      case 2: {
        if (tag == 18) {
         parse_tipo:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_tipo()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->tipo().data(), this->tipo().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "tipo");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_x;
        break;
      }

      // optional int32 x = 3;
      case 3: {
        if (tag == 24) {
         parse_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &x_)));
          set_has_x();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_y;
        break;
      }

      // optional int32 y = 4;
      case 4: {
        if (tag == 32) {
         parse_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &y_)));
          set_has_y();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:messageUpdate)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:messageUpdate)
  return false;
#undef DO_
}

void messageUpdate::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:messageUpdate)
  // required int32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // required string tipo = 2;
  if (has_tipo()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->tipo().data(), this->tipo().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "tipo");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->tipo(), output);
  }

  // optional int32 x = 3;
  if (has_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->x(), output);
  }

  // optional int32 y = 4;
  if (has_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->y(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:messageUpdate)
}

::google::protobuf::uint8* messageUpdate::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:messageUpdate)
  // required int32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // required string tipo = 2;
  if (has_tipo()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->tipo().data(), this->tipo().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "tipo");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->tipo(), target);
  }

  // optional int32 x = 3;
  if (has_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->x(), target);
  }

  // optional int32 y = 4;
  if (has_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->y(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:messageUpdate)
  return target;
}

int messageUpdate::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

    // required string tipo = 2;
    if (has_tipo()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->tipo());
    }

    // optional int32 x = 3;
    if (has_x()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->x());
    }

    // optional int32 y = 4;
    if (has_y()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->y());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void messageUpdate::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const messageUpdate* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const messageUpdate*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void messageUpdate::MergeFrom(const messageUpdate& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_tipo()) {
      set_tipo(from.tipo());
    }
    if (from.has_x()) {
      set_x(from.x());
    }
    if (from.has_y()) {
      set_y(from.y());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void messageUpdate::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void messageUpdate::CopyFrom(const messageUpdate& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool messageUpdate::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void messageUpdate::Swap(messageUpdate* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(tipo_, other->tipo_);
    std::swap(x_, other->x_);
    std::swap(y_, other->y_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata messageUpdate::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = messageUpdate_descriptor_;
  metadata.reflection = messageUpdate_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
