// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messageUpdate.proto

#ifndef PROTOBUF_messageUpdate_2eproto__INCLUDED
#define PROTOBUF_messageUpdate_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_messageUpdate_2eproto();
void protobuf_AssignDesc_messageUpdate_2eproto();
void protobuf_ShutdownFile_messageUpdate_2eproto();

class messageUpdate;

// ===================================================================

class messageUpdate : public ::google::protobuf::Message {
 public:
  messageUpdate();
  virtual ~messageUpdate();

  messageUpdate(const messageUpdate& from);

  inline messageUpdate& operator=(const messageUpdate& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const messageUpdate& default_instance();

  void Swap(messageUpdate* other);

  // implements Message ----------------------------------------------

  messageUpdate* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const messageUpdate& from);
  void MergeFrom(const messageUpdate& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // required string tipo = 2;
  inline bool has_tipo() const;
  inline void clear_tipo();
  static const int kTipoFieldNumber = 2;
  inline const ::std::string& tipo() const;
  inline void set_tipo(const ::std::string& value);
  inline void set_tipo(const char* value);
  inline void set_tipo(const char* value, size_t size);
  inline ::std::string* mutable_tipo();
  inline ::std::string* release_tipo();
  inline void set_allocated_tipo(::std::string* tipo);

  // optional int32 x = 3;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 3;
  inline ::google::protobuf::int32 x() const;
  inline void set_x(::google::protobuf::int32 value);

  // optional int32 y = 4;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 4;
  inline ::google::protobuf::int32 y() const;
  inline void set_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:messageUpdate)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_tipo();
  inline void clear_has_tipo();
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* tipo_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 y_;
  friend void  protobuf_AddDesc_messageUpdate_2eproto();
  friend void protobuf_AssignDesc_messageUpdate_2eproto();
  friend void protobuf_ShutdownFile_messageUpdate_2eproto();

  void InitAsDefaultInstance();
  static messageUpdate* default_instance_;
};
// ===================================================================


// ===================================================================

// messageUpdate

// required int32 id = 1;
inline bool messageUpdate::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void messageUpdate::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void messageUpdate::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void messageUpdate::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 messageUpdate::id() const {
  // @@protoc_insertion_point(field_get:messageUpdate.id)
  return id_;
}
inline void messageUpdate::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:messageUpdate.id)
}

// required string tipo = 2;
inline bool messageUpdate::has_tipo() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void messageUpdate::set_has_tipo() {
  _has_bits_[0] |= 0x00000002u;
}
inline void messageUpdate::clear_has_tipo() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void messageUpdate::clear_tipo() {
  if (tipo_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    tipo_->clear();
  }
  clear_has_tipo();
}
inline const ::std::string& messageUpdate::tipo() const {
  // @@protoc_insertion_point(field_get:messageUpdate.tipo)
  return *tipo_;
}
inline void messageUpdate::set_tipo(const ::std::string& value) {
  set_has_tipo();
  if (tipo_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    tipo_ = new ::std::string;
  }
  tipo_->assign(value);
  // @@protoc_insertion_point(field_set:messageUpdate.tipo)
}
inline void messageUpdate::set_tipo(const char* value) {
  set_has_tipo();
  if (tipo_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    tipo_ = new ::std::string;
  }
  tipo_->assign(value);
  // @@protoc_insertion_point(field_set_char:messageUpdate.tipo)
}
inline void messageUpdate::set_tipo(const char* value, size_t size) {
  set_has_tipo();
  if (tipo_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    tipo_ = new ::std::string;
  }
  tipo_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:messageUpdate.tipo)
}
inline ::std::string* messageUpdate::mutable_tipo() {
  set_has_tipo();
  if (tipo_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    tipo_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:messageUpdate.tipo)
  return tipo_;
}
inline ::std::string* messageUpdate::release_tipo() {
  clear_has_tipo();
  if (tipo_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = tipo_;
    tipo_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void messageUpdate::set_allocated_tipo(::std::string* tipo) {
  if (tipo_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete tipo_;
  }
  if (tipo) {
    set_has_tipo();
    tipo_ = tipo;
  } else {
    clear_has_tipo();
    tipo_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:messageUpdate.tipo)
}

// optional int32 x = 3;
inline bool messageUpdate::has_x() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void messageUpdate::set_has_x() {
  _has_bits_[0] |= 0x00000004u;
}
inline void messageUpdate::clear_has_x() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void messageUpdate::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 messageUpdate::x() const {
  // @@protoc_insertion_point(field_get:messageUpdate.x)
  return x_;
}
inline void messageUpdate::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:messageUpdate.x)
}

// optional int32 y = 4;
inline bool messageUpdate::has_y() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void messageUpdate::set_has_y() {
  _has_bits_[0] |= 0x00000008u;
}
inline void messageUpdate::clear_has_y() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void messageUpdate::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 messageUpdate::y() const {
  // @@protoc_insertion_point(field_get:messageUpdate.y)
  return y_;
}
inline void messageUpdate::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:messageUpdate.y)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_messageUpdate_2eproto__INCLUDED
